# Generated by Django 4.0.5 on 2022-06-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='status',
            new_name='member',
        ),
    ]
